@startuml

class Connection {
   - ip: String
   - port: int
   - socket: Socket
   - outputStream: DataOutputStream
   - inputStream: BufferedReader

   + Connection(ip: String, port: int)
   - createSocket(ip: String, port: int)

   # receive()
   # receive(byteLength: int)
   # receive(searchSequence: String)

   # send(content: String)
}

class Client extends Connection {
 + Client(ip: String, port: int)
 + Client()
}

note left of Client::Client
 constructor throw error
end note

note left of Client::Client()
 throw error if connection was
 not initialized by other constructor
end note

class IRCSocket {
     - client: Client

     + IRCSocket()

     + onReceive()

     + register()
     + login()
'    TODO complete missing methods


}
IRCSocket::client *-- Client

note left of IRCSocket::onReceive()
 method should be overridden
 each time new instance of class is created,
 otherwise throw an error
end note

@enduml

